### ISSUE TITLE
FeatureOfInterest

### ISSUE THREAD

**Issue by bnouhanna** [coatyio/connector.opc-ua.js#8]
**Describe the solution you'd like**
In the example provided, the producer/agent.ts  a Coaty sensor thing controller with Things, Sensors, and Observations linked to an OPC UA server specific node is created.  The question is how to link also a FeatureOfInterest describing the location of a Thing for example. 

**Describe alternatives you've considered**
I attempted to create a featureOfInterest object and add it to OpcuaSensorThingsController
`const featureofinterestPlc2Temperature: FeatureOfInterest = {
    name: "Location" ,
    objectId: Runtime.newUuid(),
    objectType: SensorThingsTypes.OBJECT_TYPE_FEATURE_OF_INTEREST,
    coreType: "CoatyObject",
    description: "The location of the Thing",
    encodingType: EncodingTypes.UNDEFINED,
    parentObjectId: sensorPlc2Temperature.objectId,
    metadata: {
        building: "comp1 production",
        floor: "Area3",
        room: "001",
    },
};`

`OpcuaSensorThingsController: {
            things: [thingPlc2],
            sensors: sensorDefinitions,
            featureOfInterest: featureofinterestPlc2Temperature,
            opcuaSensorOptions,
        },`
 But, I cannot discover it. 
I also attempted to do it as you would normally do it in a SensorThingsController using communication manager and publish advertise the created object, but I get an error can't find communication manger.

**Comment by bnouhanna** [comment]
I manage to do it by creating a SensorSourceController and advertising the feature of interest, but maybe there is a better way to do it.

**Comment by ffa500** [comment]
Not sure if I understand your use case correctly.  I suppose you just want to assign the UUID of a specific `FeatureOfInterest` object (containing location or other metadata of a thing/sensor) to each observation published by the `OpcuaSensorThingsController`, so that the consumer can look up the corresponding `FeatureOfInterest` object which must have been advertised to the consumer beforehand.

Currently, the `OpcuaSensorThingsController` doesn't support adding a specific `FeatureOfInterest` UUID to each published observation. You cannot simply "add" a `featureOfInterest` property to the configuration options of an `OpcuaSensorThingsController` as it is simply ignored. Maybe in a future release we will include this feature.

For now, you can implement this feature yourself by subclassing `OpcuaSensorThingsController` and overwriting the method `protected createObservation()` to include the `FeatureOfInterest` UUID in the created observation, like this:

```
 protected createObservation(
        container: SensorContainer,
        value: any,
        resultQuality?: string[],
        validTime?: TimeInterval,
        parameters?: { [key: string]: any; }): Observation {
        const obs = super.createObservation(
            container,
            value.result,
            resultQuality,
            validTime,
            parameters);
        // Add objectId of FeatureOfInterest for the given sensor.
        obs.featureOfInterestId = this.getFeatureOfInterestObjectFor(container.sensor)?.objectId;
        return obs;
    }
```

Then, manage your FeatureOfInterest objects in your subclass, e.g. by supporting a controller configuration option named `featureOfInterestsBySensor` which is a hash of FeatureOfInterest objects mapped by sensor object ID, like this:

```
featureOfInterestsBySensor: {
    "<sensorPlc2Temperature.objectId>": { name: "Location" , objectId: Runtime.newUuid(), objectType: SensorThingsTypes.OBJECT_TYPE_FEATURE_OF_INTEREST, coreType: "CoatyObject", description: "The location of the Thing", encodingType: EncodingTypes.UNDEFINED, parentObjectId: sensorPlc2Temperature.objectId, metadata: { building: "comp1 production", floor: "Area3", room: "001", }, },
    "<sensorPlc1Temperature.objectId>": { ... },
}
```

and define a method in your subclass retrieving the FeatureOfInterest object for a given sensor from this configuration option.

Next. advertise all the configured FeatureOfInterest objects on initialization, i.e. in the `onCommunicationManagerStarting` method and make them discoverable by other agents, like this:

```
onCommunicationManagerStarting() {
    // Advertise each of the configured FeatureOfInterst objects 
   Object.values(this.options.featureOfInterestsBySensor).forEach(foi => 
         this.communicationManager.publishAdvertise(AdvertiseEvent.withObject(foi));
   this.communicationManager
            .observeDiscover()
            .pipe(filter((event: DiscoverEvent) =>
                (event.data.isDiscoveringTypes &&
                    event.data.isObjectTypeCompatible(SensorThingsTypes.OBJECT_TYPE_FEATURE_OF_INTEREST))))
            .subscribe(event =>
                Object.values(this.options.featureOfInterestsBySensor).forEach(foi => 
                     event.resolve(ResolveEvent.withObject(foi)));
}
```
 
Finally, don't forget to register your newly created class in the `controllers` options of your container components and specify the proper controller config option `featureOfInterestsBySensor`.

On the consumer side, you can now combine observeAdvertise and publishDiscover in an `onCommunicationManagerStarting` method to observe these objects, like this:

```
const discoveredTasks$ = this.communicationManager
    .publishDiscover(DiscoverEvent.withObjectTypes([SensorThingsTypes.OBJECT_TYPE_FEATURE_OF_INTEREST]))
    .pipe(
        filter(event => event.eventData.object !== undefined),
        map(event => event.eventData.object as FeatureOfInterest)
    );

const advertisedTasks$ = this.communicationManager
    .observeAdvertiseWithObjectType(SensorThingsTypes.OBJECT_TYPE_FEATURE_OF_INTEREST)
    .pipe(
        map(event => event.eventData.object as FeatureOfInterest)
        filter(foi=> foi!== undefined)
    );

return merge(discoveredTasks$, advertisedTasks$)
            .subscribe(foi=> {
                // Handle both discovered and advertised FeatureOfInterest objects as they are emitted...
            });
```

BTW, there is also a much easier alternative to achieve the same result without using the `FeatureOfInterest` feature at all. 

Simply add the location information like `{ building: "comp1 production", floor: "Area3", room: "001", }` to the `metadata` property of a Sensor object. This property can include any additional application-specific data. As the sensors are advertised and made discoverable by the  `OpcuaSensorThingsController` automatically, you don't need to do anything else on the producer side. On the consumer side, you get the location information along with the observed sensors made available by the `ThingSensorObservationObserverController`.

Note that the second approach assumes that the "location" of your sensors won't change during run time of the system. The first approach handles dynamic location changes of e.g. mobile sensors.

**Comment by bnouhanna** [comment]
I went for the first option. Thanks, this answers my question.
